project:
  type: website
  resources:
    - Fonts

execute:
  freeze: auto

website:
  title: "The Safer Parks Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - guide.qmd
      - data.qmd
      - partners.qmd
      - text: Launch
        href: https://safer-parks.github.io/archived-dashboard-wyca/dashboard.html
        target: _blank

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    include-before-body: main.html
    



