project:
  type: website
  resources:
    - Fonts

execute:
  freeze: auto

website:
  title: "The Safer Parks Dashboard"
  google-analytics: "G-39QR6T27XH"
  cookie-consent:
    type: express
    style: interstitial
    palette: light
    policy-url: https://murphyqm.github.io/Safer-Parks.github.io/privacy.html
  favicon: assets/icon-parks4.svg
  body-footer: <div class="footer-wrapper  column-page"><p><small>© University of Leeds, 2025 | <a href="about.html">About</a> | <a href="privacy.html">Privacy & Cookies</a> | <a href="https://www.leeds.ac.uk/about/doc/accessibility-statement" target="_blank" rel="noopener">Accessibility</a></small></p>  <p><small><a href="#" id="open_preferences_center">Update cookies preferences</a></small></p>  <p><small><img src="assets/partners/leeds_uni.png" alt="University of Leeds logo" width="200px"></small></p></div>
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - guide.qmd
      - data.qmd
      - partners.qmd
      - text: Launch
        href: https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.cloud.microsoft%2FPages%2FResponsePage.aspx%3Fid%3DqO3qvR3IzkWGPlIypTW3y_21PdTtSidAqW-TSzvWOgxUMzk3UlRYQjJXTUMwNlQyVk1RREUxVjM1Qy4u&data=05%7C02%7C%7Ca12ccb7fa0fe445c7a7508df1efa6611%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C639263732943170416%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=s5tWC7RH%2B3qM5xB6FXmxefbxXvlrComEvu52l%2F1Xjlc%3D&reserved=0

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    include-before-body: main.html
    



