project:
  type: website
  resources:
    - Fonts

execute:
  freeze: auto

website:
  title: "The Safer Parks Dashboard"
  favicon: assets/icon-parks4.svg
  body-footer: <div class="footer-wrapper  column-page"><p><small>© University of Leeds, 2025 | <a href="about.html">About</a> | <a href="privacy.html">Privacy & Cookies</a> | <a href="https://www.leeds.ac.uk/about/doc/accessibility-statement" target="_blank" rel="noopener">Accessibility</a></small></p>  <p><small><a href="#" id="open_preferences_center">Update cookies preferences</a></small></p>  <p><small><img src="assets/partners/leeds_uni.png" alt="University of Leeds logo" width="200px"></small></p></div>
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - guide.qmd
      - data.qmd
      - partners.qmd
      - text: Launch
        href: launch.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    include-before-body: main.html
    



